author: The Under the Surface Project
bibtex_bibfiles:
- ../references.bib
html:
  extra_footer: '<p>Logo based on: <a href="https://unsplash.com/photos/At_r0TuqL8o">https://unsplash.com/photos/At_r0TuqL8o</a></p>

    '
  use_issues_button: false
  use_repository_button: true
logo: logo.jpg
repository:
  branch: main
  path: de
  url: https://github.com/scmmmh/under-the-surface
sphinx:
  config:
    language: de
  extra_extensions:
  - uedition
title: "Unter der Oberfl\xE4che"
